import { StyleSheet } from "react-native";

export const recordModalStyles = StyleSheet.create({
  recordModal: {
    borderWidth: 0,
    borderRadius: 20,
    width: "100%",
    maxWidth: 390,
    maxHeight: "90%",
    alignSelf: "center",
    overflow: "hidden",
  },
  recordScroll: { flexShrink: 1, maxHeight: "100%" },
  recordBody: { padding: 16, paddingBottom: 20 },
  moneyInputWrap: {
    height: 56,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  moneyPrefix: { fontSize: 18, fontWeight: "700", marginRight: 14 },
  moneyInput: {
    flex: 1,
    height: "100%",
    fontSize: 18,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  moneyPreview: {
    maxWidth: 118,
    marginLeft: 10,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  calcToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: -10,
    marginBottom: 18,
  },
  calcChip: {
    minWidth: 38,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  calcChipText: { fontSize: 17, fontWeight: "700" },
  recordActions: { flexDirection: "row", gap: 10, marginTop: 8 },
  recordCancel: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  recordSubmit: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  recordCancelText: { fontSize: 15, fontWeight: "700" },
  recordSubmitText: { fontSize: 15, fontWeight: "700" },
});
